openapi: 3.0.3
info:
  title: API de gestion de tâches
  description: API pour créer, lire, mettre à jour et supprimer des tâches
  version: 1.0.0
servers:
  - url: https://api.example.com
    description: Serveur principal

paths:
  /tasks:
    get:
      summary: Récupérer toutes les tâches
      description: Retourne la liste de toutes les tâches
      responses:
        '200':
          description: Liste des tâches récupérée avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
                - id: 2
                  title: "Réviser pour l'examen"
                  completed: true

    post:
      summary: Créer de nouvelles tâches
      description: Crée une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskInput'
            example:
              - title: "Faire les courses"
                completed: false
              - title: "Réviser pour l'examen"
                completed: false
      responses:
        '201':
          description: Tâches créées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
                - id: 2
                  title: "Réviser pour l'examen"
                  completed: false

    delete:
      summary: Supprimer plusieurs tâches
      description: Supprime une liste de tâches basée sur leurs identifiants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
              description: Liste des identifiants des tâches à supprimer
            example: [1, 3, 5]
      responses:
        '200':
          description: Tâches supprimées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  title: "Faire les courses"
                  completed: false
                - id: 3
                  title: "Appeler le médecin"
                  completed: true

  /tasks/{id}:
    get:
      summary: Récupérer une tâche par ID
      description: Retourne une tâche spécifique basée sur son identifiant
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de la tâche
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Faire les courses"
                completed: false
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Task not found"

    delete:
      summary: Supprimer une tâche par ID
      description: Supprime une tâche spécifique et retourne la tâche supprimée
      parameters:
        - name: id
          in: path
          required: true
          description: Identifiant unique de la tâche à supprimer
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Tâche supprimée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                title: "Faire les courses"
                completed: false
        '404':
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                error: "Task not found"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          description: Identifiant unique de la tâche
          example: 1
        title:
          type: string
          description: Titre de la tâche
          example: "Faire les courses"
        completed:
          type: boolean
          description: État de completion de la tâche
          example: false
      required:
        - id
        - title
        - completed

    TaskInput:
      type: object
      properties:
        title:
          type: string
          description: Titre de la tâche
          example: "Faire les courses"
        completed:
          type: boolean
          description: État de completion de la tâche
          example: false
      required:
        - title
        - completed

    Error:
      type: object
      properties:
        error:
          type: string
          description: Message d'erreur
          example: "Task not found"
      required:
        - error